[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "selfhosted-google-docs"
authors = [{name = "jkdev", email = "jakob.kampichler@gmail.com"}]
dynamic = ["version", "description"]
